<Project Sdk="Godot.NET.Sdk/4.4.1">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>FleetingCity</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="FleetingCity.BAL/FleetingCity.BAL.csproj" />
  </ItemGroup>
</Project>